name: DeathBan
version: '1.2.1'
main: com.jqshuv.deathban.DeathBan
api-version: '1.13'
author: Jqshuv
permissions:
  deathban.immune:
    description: Gives you immunity to death bans.
    default: op