name: DeathBan
version: '1.3.0'
main: com.jqshuv.deathban.DeathBan
api-version: '1.13'
folia-supported: true
author: Jqshuv
permissions:
  deathban.immune:
    description: Gives you immunity to death bans.
    default: op